services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs-server

    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # 单个日志文件的最大大小
        max-file: "3"    # 保留的最大日志文件数

    extra_hosts:
     - "rustfs1:10.100.13.28"
     - "rustfs2:10.100.13.29"
     - "rustfs3:10.100.13.30"
     - "rustfs4:10.100.13.31"

    environment:
      - RUSTFS_VOLUMES=rustfs{1...4}:9000/data/rustfs{1..4}  # Define 4 storage  必须以正整数，官方中以0开始，0是非负整数，不是正整数, 官方给出的是两个点，必须是三个点,但是使用mkdir创建文件夹的时候要用两个点，容器启动后会有一个文件夹rustfs{1..4}，这是正常现象
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_EXTERNAL_ADDRESS=:9000  # Same as internal since no port mapping
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_LOG_LEVEL=info
    volumes:
    # 如果有多个磁盘，需要将每块磁盘挂载上去，本文档中只挂载了一个路径，挂载点需要与RUSTFS_VOLUMES对应起来
      - ./data/rustfs1:/data/rustfs1
      - ./data/rustfs2:/data/rustfs2
      - ./data/rustfs3:/data/rustfs3
      - ./data/rustfs4:/data/rustfs4
      - ./logs:/app/logs
      # - deploy/data/certs/:/opt/tls # TLS configuration, you should create tls directory and put your tls files in it and then specify the path here
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://localhost:9000/health && curl -f http://localhost:9001/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    network_mode: host


