version: '3.1'

services:
  elastic-1:
    image: elasticsearch:8.13.0
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # 单个日志文件的最大大小
        max-file: "1"    # 保留的最大日志文件数
    shm_size: '1gb'
    restart: always
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - "TZ=Asia/Shanghai"
      - "ELASTIC_PASSWORD=010.Tydic"
    volumes:
      - ./ES_DATA:/usr/share/elasticsearch/data
      - ./ES-plugins:/usr/share/elasticsearch/plugins
    networks:
      - custom-network

  kibana:
    image: kibana:8.10.4
    shm_size: '1gb'
    restart: always
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    environment:
      - TZ=Asia/Shanghai
      - ES_JAVA_OPTS=-Xmx1024M -Xms1024M
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./conf/http_ca.crt:/usr/share/kibana/config/certs/server.crt
    networks:
      - custom-network

# 创建网络
networks:
  custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.25.2.0/24