services:
  tianshu-cat:
    image: tydicllm_910b3:v1
    container_name: tianshu-cat

    restart: always
    privileged: true
    ipc: host
    pid: host
    working_dir: /usr/local/Ascend/mindie/latest/mindie-service

    # 限制容器本身日志大小
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

    # 由于内部无法将端口监听到0.0.0.0，因此无法使用端口映射的方式
    network_mode: host
    
    # 设置环境变量，将mindie日志输出到标准输出
    environment:
      - MINDIE_LOG_TO_STDOUT=1
    
    devices:
      - /dev/davinci0:/dev/davinci0
      - /dev/davinci1:/dev/davinci1
      - /dev/davinci2:/dev/davinci2
      - /dev/davinci3:/dev/davinci3
      - /dev/davinci4:/dev/davinci4
      - /dev/davinci5:/dev/davinci5
      - /dev/davinci6:/dev/davinci6
      - /dev/davinci7:/dev/davinci7
      - /dev/davinci_manager:/dev/davinci_manager
      - /dev/devmm_svm:/dev/devmm_svm
      - /dev/hisi_hdc:/dev/hisi_hdc

    volumes:
      - /usr/local/dcmi:/usr/local/dcmi
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
      - /etc/ascend_install.info:/etc/ascend_install.info
      - /etc/vnpu.cfg:/etc/vnpu.cfg
      - ./models:/models
      - ./conf/cat_config.json:/usr/local/Ascend/mindie/latest/mindie-service/conf/config.json
      - ./logs:/models/logs
      - ./start_tianshu_cat.sh:/app/start_tianshu_cat.sh

    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 2 bash -c '</dev/tcp/127.0.0.1/19998'"]
      interval: 5s         # 每 5 秒检测一次
      timeout: 3s          # 检查超时 3 秒
      retries: 5           # 连续 5 次失败才标记为 unhealthy
      start_period: 120s    # 容器启动后等待 10 秒再开始健康检查
    # 如果启动多实例，需要开启depends_one ,逐个启动，不然会混乱，启动失败
    # depends_on:
    #   tianshu-prd:
    #     condition: service_healthy
    command: >
      sh /app/start_tianshu_cat.sh
    
