 # 安装依赖
apt install -y  \
libvips \
libvips-dev \
libvips-tools \
tesseract-ocr \
tesseract-ocr-chi-sim \
imagemagick \
libmagickwand-dev \
ruby-dev \
build-essential  && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*



# 安装despeck
gem install despeck