version: '3.9'

services:
  redis:
    image: redis:5.0.14
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/nbchat/redis:/data
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 6379:6379
    networks:
      - nbchat