version: '3.9'

services:
  redis:
    image: 192.168.10.212/middleware/redis:6.2.14
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # 单个日志文件的最大大小
        max-file: "1"    # 保留的最大日志文件数
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redisdata:/data
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 6379:6379
    networks:
      - nbchat