services:
  nginx:
    image: 192.168.10.212/middleware/nginx_arm64:1.26.2
    privileged: true
    ipc: host
    shm_size: 4g
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # 单个日志文件的最大大小
        max-file: "1"    # 保留的最大日志文件数
    restart: always
    hostname: nginx
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - 8080:8080
      - 24980:24980
      - 23980:23980
    networks:
      - custom-network

# 创建网络
networks:
  custom-network:
    driver: bridge