services:
  mineru_api_1:
    container_name: mineru_api_1
    image: mineru2.0:v1
    privileged: true
    ports:
      - "20001:30001"
    volumes:
      - ./envs/mineru:/opt/miniconda/envs/mineru
      - ./data:/data
      - ./modles:/modles
      - ./mineru.json:/root/mineru.json
    environment:
      - MINERU_MODEL_SOURCE=local
      - CUDA_VISIBLE_DEVICES=2,3
    shm_size: "32g"
    ipc: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all    # 这里写 all 就是所有 GPU
              capabilities: [gpu]
    restart: always
    command:  
      mineru-api --host 0.0.0.0 --port 30001
    # 如需启用 torch compile，取消下一行注释
    # command: mineru-api --host 0.0.0.0 --port 30001 --enable-torch-compile


  mineru-server:
    container_name: mineru-server
    image: mineru2.0:v1
    privileged: true
    ipc: host
    shm_size: 32g
    restart: always
    runtime: nvidia
    environment:
      - MINERU_MODEL_SOURCE=local
      - CUDA_VISIBLE_DEVICES=2,3
    volumes:
      - ./envs/mineru:/opt/miniconda/envs/mineru
      - ./data:/data
      - ./modles:/modles
      - ./mineru.json:/root/mineru.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all    # 这里写 all 就是所有 GPU
              capabilities: [gpu]
            # 另一种写法
            # - driver: nvidia
            #   device_ids: ['0']
            #   capabilities: [gpu]
    ports:
      - "30000:30000"
    command: >
      mineru-sglang-server --host 0.0.0.0 --port 30000 