version: '3.1'
services:
  nacos_cluster:
    image: nacos/nacos-server:v2.4.0.1
    shm_size: '1gb'
    restart: always
    container_name: nacos-1
    hostname: nacos-1
    network_mode: host
    environment:
      - "TZ=Asia/Shanghai"
      - "NACOS_AUTH_ENABLE=true"
      - "NACOS_SERVERS=172.16.91.60:8848 172.16.91.61:8848 172.16.91.62:8848"
      - "SPRING_DATASOURCE_PLATFORM=mysql"
      - "MYSQL_SERVICE_HOST=172.16.91.226"
      - "MYSQL_SERVICE_DB_NAME=nacos_prod"
      - "MYSQL_SERVICE_PORT=3306"
      - "MYSQL_SERVICE_USER=zmuser"
      - "MYSQL_SERVICE_PASSWORD=OmPkRWCxH1EsrGT0"
      - "MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
      - "NACOS_AUTH_IDENTITY_KEY=2222"
      - "NACOS_AUTH_IDENTITY_VALUE=2xxx"
      - "NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789"
    volumes:
      - ./logs:/home/nacos/logs
