version: '3.1'
services:
  elastic-1:
    image: 192.168.10.212/middleware/mysql:8.0.37
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # 单个日志文件的最大大小
        max-file: "3"    # 保留的最大日志文件数
    shm_size: '1gb'
    restart: always
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_ROOT_PASSWORD=DBAuser_pass_001"
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - ./my_data:/var/lib/mysql
      - ./my_init:/docker-entrypoint-initdb.d
    networks:
      - custom-network

# 创建网络
networks:
  custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.25.2.0/24
