services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    command: minio server --compat --address 0.0.0.0:9000 --console-address 0.0.0.0:9999 http://172.16.91.160/minio_data http://172.16.91.161/minio_data http://172.16.91.162/minio_data http://172.16.91.166/minio_data 
    restart: always
    network_mode: host
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: u6sa34ulpUbjc3a9Ig96hJMYas3GqckB
    volumes:
      - /data/minio_data:/minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3