services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    extra_hosts:
     - "minio1:172.16.95.87"
     - "minio2:172.16.95.88"
     - "minio3:172.16.95.89"
     - "minio4:172.16.95.90"
     # 取决于有多少块磁盘修改minio_data{1...4}
    command: minio server --compat --address 0.0.0.0:9000 --console-address 0.0.0.0:9999 http://minio{1...4}/minio_data{1...4}
    restart: always
    network_mode: host
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: u6sa34ulpUbjc3a9Ig96hJMYas3GqckB
    volumes:
      - /data/minio_data:/minio_data
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/127.0.0.1/9000"]
      interval: 10s
      timeout: 20s
      retries: 3